language: objective-c
osx_image: xcode11.4
xcode_sdk: iphonesimulator11.4
script:
    - set -o pipefail
    - travis_retry xcodebuild -workspace GKNavigationBarSwift.xcworkspace -scheme "Example" -destination "platform=iOS Simulator,name=iPhone 6"
